# Generated by Django 5.2.5 on 2025-08-23 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper', '0002_company_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='url',
        ),
        migrations.AddField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
